### ISSUE TITLE
bosh release is not self contained. requires internet access

### ISSUE THREAD

**Issue by poblin-orange** [cloudfoundry-community/nginx-release#1]
Trying to use the nginx release behind our corporate proxies.
Seems that it requires internet access at compilation time. Why not use bosh blobs to package ?

trace below:
  Started compiling packages > nginx-1.6.2/04593454a1fe958c4f523ae266dfdbb433eccf6d. Failed: Action Failed get_task: Task 077071a1-c905-4ee9-52c8-0421ac16b771 result: Compiling package nginx-1.6.2: Running packaging script: Command exited with 100; Stdout: Err http://ppa.launchpad.net trusty Release.gpg  
  Unable to connect to ppa.launchpad.net:http:  
Ign http://ppa.launchpad.net trusty Release  
Ign http://ppa.launchpad.net trusty/main amd64 Packages/DiffIndex  
Err http://ppa.launchpad.net trusty/main Translation-en

**Comment by mehtaphysical** [comment]
i agree. should add pcre as a package. would you accept a pr?

**Comment by poblin-orange** [comment]
Seems bosh release is already using nginx, and packages it offline
https://github.com/cloudfoundry/bosh/blob/672b542911f6056da2ebb1558a76b3bd74f3cf00/release/packages/nginx/spec

Could reuse the package easily with bosh-gen extract-pkg
https://github.com/cloudfoundry-community/bosh-gen

**Comment by mehtaphysical** [comment]
Nginx is packaged. But pcre isn't. Right now pcre is installed with apt-get

**Comment by poblin-orange** [comment]
correct. Just did a test repackaging nginx from bosh-release (including pcre)
seems ok
https://github.com/Orange-OpenSource/nginx-release

**Comment by mehtaphysical** [comment]
Nice! I think you should do a pr to this repo and get those changes merged in

**Comment by poblin-orange** [comment]
done. https://github.com/cloudfoundry-community/nginx-release/pull/2

**Comment by bsnchan** [comment]
Looks like the PR has already been merged.

**Comment by cunnie** [comment]
@poblin-orange : the latest release (v3, nginx 1.11.1) should be self-contained. Let me know if you run into any problems.
