### ISSUE TITLE
feature: add nginx sub-module

### ISSUE THREAD

**Issue by lrstanley** [cloudfoundry-community/nginx-release#16]
Thoughts on adding the http_sub_module? Should just be an additional flag during build.

http://nginx.org/en/docs/http/ngx_http_sub_module.html

It's something that I believe is auto-included with quite a few distributions (e.g. Ubuntu) by default. I'd like to take advantage of it to inject references to css/js for a backend reverse proxy that doesn't support pre/post includes (i.e. replace `</head>` with `<link etc... /></head>` in responses, and would prefer to not have to create my own release.

Thanks!

**Comment by cunnie** [comment]
I'll try to remember next time I update it, but I've lost the AWS keys, so I may have trouble publishing the blobs.

If you need it _right now_, you're probably better off forking & building your own custom release.

**Comment by cunnie** [comment]
If the person I'm trying to get has time, we'll try to bump it this Saturday or next.
