### ISSUE TITLE
Upgrade Nginx Version to 1.9.10

### ISSUE THREAD

**Issue by jdesulme** [cloudfoundry-community/nginx-release#20]
The nginx version hasn't been updated in over a year. With the latest version available is now at 1.19.10. Hoping that an update to the release can be made. http://nginx.org/en/CHANGES

**Comment by cunnie** [comment]
Hi @jdesulme I'll try to get to it soon, thanks for your patience.

**Comment by jdesulme** [comment]
That was pretty quick... Thank you very much

**Comment by cunnie** [comment]
You're welcome, @jdesulme

**Comment by jdesulme** [comment]
Hey @cunnie my team tried to use the latest release but found you no longer have the .tgz release available anymore. Seems like it broke as part of 1.19.1 as well. 
https://github.com/cloudfoundry-community/nginx-release/releases

**Comment by cunnie** [comment]
@jdesulme Get your tarballs from <https://bosh.io/releases/>, search for "nginx-release"; get the community version.

bosh.io builds the tarballs automatically, calculates the SHA, and provides instructions, and I got tired of doing that stuff manually.
