### ISSUE TITLE
configuring client key/certs for reverse proxy

### ISSUE THREAD

**Issue by ywei2017** [cloudfoundry-community/nginx-release#21]
I am facing the question of "how to configure the client key/certs in the reverse-proxy setting?"  There are 2 possible solutions

1. add a pairt of "client_ssl_key" and "client_ssl_cert" attributes. This is simple to do, but it only works for a single upstream.
2. add a generic array attribute like "config_attributes", and use a template to generate the files. In the following example, file "key1" will contain "value1" as the content, file "key2" will have "value2" as the content, and file "upstream_server" with "www.mydomain.com" as the content. These generated files can be referenced in the nginx.conf (such as `/var/vcap/jobs/nginx/etc/attributes/key1`):
```
config_attributes:
- key1: value1
- key2: value2 
- upstream_server: www.mydomain.com
```

I would propose option 2, and will be happy to submit a PR. Another use is setting the upstream URL. Instead of hard-coding in nginx.conf, you can now use a keyword placeholder, and use pre_start to populate with a configured value.

Arguably, with option 2, you can do away with `ssl_key` and `ssl_chained_cert`, but they should be retained for backward compatibility, at least for sometime.

Let me know your thoughts.

**Comment by cunnie** [comment]
Why not use the [pre-start](https://github.com/cloudfoundry-community/nginx-release/blob/master/jobs/nginx/templates/pre-start.erb) template to create the files containing multiple keys? e.g.

```shell
cat > /tmp/key1 <<EOF
--- BEGIN ...
--- END
EOF
cat > /tmp/key2 <<EOF
--- BEGIN ...
--- END
EOF
```

An additional property shouldn't be necessary to accomplish what you're trying to do.

**Comment by ywei2017** [comment]
@cunnie That is a fair argument.

One of the challenges is how do I configure the keys/certs in the deployment yaml, with `spruce` or `jq`? One thing I can do it to split the `pre_start` script into multiple slices, and use (( concat slice1 $ENV1 slie2 )). 

So I think I am good for now. no need to make it more complicated.
