### ISSUE TITLE
Make nginx.conf configurable in a fine granular way

### ISSUE THREAD

**Issue by Kiemes** [cloudfoundry-community/nginx-release#4]
Hi @cunnie, greetings from Germany. Hope you are doing fine. I am currently writing a BOSH release for a JetBrains license server. I am using your nginx BOSH release as a reverse proxy to enable TLS for the license server. I am wondering if you thought about using configurable nginx.conf. I want to make the port for the license server configurable. That means I have to use the same port in the nginx.conf as well. At the moment, the user has to specify the port in two places, once for my config and a second time in the nginx.conf
My current nginx.conf looks like this:
```
worker_processes  1;
error_log /var/vcap/sys/log/nginx/error.log   info;
events {
  worker_connections  1024;
}
http {
  include /var/vcap/packages/nginx/conf/mime.types;
  default_type  application/octet-stream;
  sendfile        on;
  keepalive_timeout  65;
  server_names_hash_bucket_size 64;
  # redirect HTTP to HTTPS
  server {
    server_name _; # invalid value which will never trigger on a real hostname.
    listen 80;
    rewrite ^ https://localhost$request_uri?;
    access_log /var/vcap/sys/log/nginx/localhost-access.log;
    error_log /var/vcap/sys/log/nginx/localhost-error.log;
  }
  server {
    listen       443 ssl;
    server_name  localhost;
    ssl_certificate      /var/vcap/jobs/nginx/etc/ssl_chained.crt.pem;
    ssl_certificate_key  /var/vcap/jobs/nginx/etc/ssl.key.pem;
    ssl_session_cache    shared:SSL:1m;
    ssl_session_timeout  5m;
    ssl_prefer_server_ciphers  on;
    location / {
      proxy_set_header    X-Forwarded-Host    $http_host;
      proxy_set_header    X-Forwarded-Proto   https;
      proxy_http_version  1.1;
      proxy_set_header    Host                $host;
      proxy_set_header    X-Forwarded-For     $remote_addr;
      proxy_set_header    X-Real-IP           $remote_addr;
      proxy_pass          http://127.0.0.1:8888/;
    }
  }
}
```
The part I am talking about is the last line. Currently I have to hardcode the license server port to 8888. 

I was thinking about alternatives in the [nginx.conf.erb](https://github.com/cloudfoundry-community/nginx-release/blob/master/jobs/nginx/templates/nginx.conf.erb) as a possible solution.
```
<% if_p('nginx_conf') %>
<%= p('nginx_conf') %>
<% end %>

<% if_p('nginx_conf_reverse_proxy') %>
worker_processes  1;
error_log /var/vcap/sys/log/nginx/error.log   info;
events {
  worker_connections  1024;
}
http {
  include /var/vcap/packages/nginx/conf/mime.types;
  default_type  application/octet-stream;
  sendfile        on;
  keepalive_timeout  65;
  server_names_hash_bucket_size 64;
  # redirect HTTP to HTTPS
  server {
    server_name _; # invalid value which will never trigger on a real hostname.
    listen 80;
    rewrite ^ https://localhost$request_uri?;
    access_log /var/vcap/sys/log/nginx/localhost-access.log;
    error_log /var/vcap/sys/log/nginx/localhost-error.log;
  }
  server {
    listen       443 ssl;
    server_name  localhost;
    ssl_certificate      /var/vcap/jobs/nginx/etc/ssl_chained.crt.pem;
    ssl_certificate_key  /var/vcap/jobs/nginx/etc/ssl.key.pem;
    ssl_session_cache    shared:SSL:1m;
    ssl_session_timeout  5m;
    ssl_prefer_server_ciphers  on;
    location / {
      proxy_set_header    X-Forwarded-Host    $http_host;
      proxy_set_header    X-Forwarded-Proto   https;
      proxy_http_version  1.1;
      proxy_set_header    Host                $host;
      proxy_set_header    X-Forwarded-For     $remote_addr;
      proxy_set_header    X-Real-IP           $remote_addr;
      proxy_pass          http://127.0.0.1:<%= p('forward_to_port') %>/;
    }
  }
}
<% end %>
```
With BOSH links it should be possible to use the same property in both places (my definition of the port and here as the consumer).

Any ideas how we easily could enable such a more fine granular configuration of `nginx_conf` instead of pasting the whole fixed content?
Best regards, Tom

**Comment by cunnie** [comment]
@Kiemes Tom I'm so sorry I didn't see this earlier — I have fallen woefully behind on my GitHub email. My apologies.

I like your idea — submit a Pull Request with the change & documentation in README.md on how to use the new property you're adding & I'll merge it.

**Comment by cunnie** [comment]
@Kiemes I'm closing this issue because it has been open for a while and I don't see any resolution in the near term. That being said, I'm open to ideas and you can always re-open this issue.

Stop by next time you're in the States!
